version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
    "dist/**",
    "node_modules/**",
    "public/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest",
    "cypress"
  ]
  plugins = ["vue"]
  style_guide = "standard"
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
